if(Meteor.users.findOne({username: 'tyler'}) ) {
  Trackers.remove({})
  var myUserid = Meteor.users.findOne({username: 'tyler'})._id
  var tracker1 = addTracker({trackerName: 'Happiness', userId: myUserid})
  var tracker2 = addTracker({trackerName: 'Stress', userId: myUserid})
  var tracker3 = addTracker({trackerName: 'Back Pain', userId: myUserid})
  addTracker({trackerName: 'Invisible Tracker', userId: 'acbdfshsdfsdfb'})

  //Add demo data
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,2,19) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,2,20) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,2,21) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,2,22) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,2,23) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,2,24) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,2,25) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,2,26) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,2,27) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,2,28) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,3,1) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,3,2) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,3,3) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,3,4) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,3,5) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,3,6) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,3,7) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,3,8) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,3,9) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,3,10) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,3,11) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,3,12) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,3,13) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 1, date: new Date(2014,3,14) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: 0, date: new Date(2014,3,15) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,3,16) });
  addDataToTracker({ userId: myUserid, trackerId: tracker1, vote: -1, date: new Date(2014,3,17) });

  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,2,19) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,2,20) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,2,21) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,2,22) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,2,23) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,2,24) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,2,25) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,2,26) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,2,27) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,2,28) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,3,1) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,3,2) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,3,3) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,3,4) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,3,5) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,3,6) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,3,7) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,3,8) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,3,9) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,3,10) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,3,11) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,3,12) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,3,13) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,3,14) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 0 , date: new Date(2014,3,15) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: 1, date: new Date(2014,3,16) })
  addDataToTracker({ userId: myUserid, trackerId: tracker2, vote: -1, date: new Date(2014,3,17) })

  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,2,19) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,2,20) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,2,21) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,2,22) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,2,23) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,2,24) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,2,25) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,2,26) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,2,27) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,2,28) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,3,1) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,3,2) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,3,3) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,3,4) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,3,5) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,3,6) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,3,7) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,3,8) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,3,9) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,3,10) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,3,11) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,3,12) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,3,13) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,3,14) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 0 , date: new Date(2014,3,15) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: 1, date: new Date(2014,3,16) })
  addDataToTracker({ userId: myUserid, trackerId: tracker3, vote: -1, date: new Date(2014,3,17) })
}


if(Meteor.users.findOne({username: 'demo'}) ) {
  var demoUserId = Meteor.users.findOne({username: 'demo'})._id

  Trackers.remove({userId: demoUserId})
  var tracker1 = addTracker({trackerName: 'Happiness', userId: demoUserId})
  var tracker2 = addTracker({trackerName: 'Stress', userId: demoUserId})
  var tracker3 = addTracker({trackerName: 'Personal Life', userId: demoUserId})
  var tracker4 = addTracker({trackerName: 'Work Life', userId: demoUserId})

addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,3,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,3,31) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,4,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,4,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,5,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,5,31) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,6,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,6,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,6,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,6,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,6,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: 1,date: new Date(2014,6,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker1, vote: -1,date: new Date(2014,6,7) })

addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,3,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,3,31) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,4,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,4,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,5,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,5,31) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,6,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,6,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,6,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,6,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: 1,date: new Date(2014,6,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,6,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker2, vote: -1,date: new Date(2014,6,7) })

addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,3,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,3,31) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,4,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,4,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,5,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,5,31) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,6,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,6,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: -1,date: new Date(2014,6,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,6,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,6,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,6,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker3, vote: 1,date: new Date(2014,6,7) })

addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,3,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,3,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,3,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,3,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,3,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,3,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,3,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,3,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,3,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,3,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,3,31) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,4,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,4,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,7) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,8) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,9) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,10) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,11) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,12) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,13) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,14) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,15) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,16) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,17) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,18) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,19) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,20) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,21) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,22) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,23) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,24) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,25) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,26) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,27) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,28) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,5,29) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,30) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,5,31) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,6,1) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,6,2) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,6,3) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,6,4) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: 1,date: new Date(2014,6,5) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,6,6) })
addDataToTracker({ userId: demoUserId, trackerId: tracker4, vote: -1,date: new Date(2014,6,7) })
}

